name: release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Replace Version in Chart.yaml
        run: sed -i 's/CHART_VERSION/0.1.69/g' ./installer-chart/chart/Chart.yaml

      - name: Replace App Version in Chart.yaml
        run: sed -i 's/APP_VERSION/0.4.3/g' ./installer-chart/chart/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0

      - name: Package
        run: |
          helm package ./installer-chart/chart

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
